name: auto_test

# This action is triggered:
# 1. when someone creates a pull request for a merge to the main branch
# 2. when changes are merged into the main branch (via a pull request)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Below are jobs, each of which runs sequentially.
jobs:
  # This job builds the box model and runs our test suite.
  build:
    # A build matrix storing all desired configurations.
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest]
        build-type: [Debug, Release]
        fp-precision: [single, double]
        pack-size: [1, 4]

    runs-on: ${{ matrix.os }}

#    # Pre-fab container with third-party libs installed.
#    container: coherellc/haero-tpl:${{ matrix.build-type }}-${{ matrix.fp-precision }}-pack-size-${{ matrix.pack-size }}

    # Environment variables
    env:
      FC: gfortran
      CI: 1   # indicates that we are running in a CI environment.

    # Steps for building and running tests.
    steps:

    - name: Installing dependencies
      run: |
        apt-get update && apt-get install -y --no-install-recommends \
        autoconf \
        clang-format \
        cmake \
        libopenmpi-dev \
        gcc \
        g++ \
        gfortran \
        git \
        make \
        pkg-config \
        ca-certificates

    - name: Checking out repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: recursive

#    - name: Checking out MAM4 box model (no submodules)
#      uses: actions/checkout@v2
#      with:
#        repository: git@github.com:eagles-project/mam_refactor.git
#        path: mam4-box
#        token: ${{ secrets.MAM4BOX_TOKEN }}
#        submodules: false

    - name: Configuring haero (${{ matrix.build-type }}, ${{ matrix.fp-precision }} precision, pack size=${{ matrix.pack-size }})
      run: |
        ./setup build
        cd build
        cmake \
          -DCMAKE_INSTALL_PREFIX=`pwd`/build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
          -DCMAKE_CXX_COMPILER=c++ \
          -DCMAKE_C_COMPILER=cc \
          -DCMAKE_Fortran_COMPILER=gfortran \
          -DHAERO_ENABLE_CHEMISTRY=OFF \
          -DHAERO_ENABLE_GPU=OFF \
          -DHAERO_ENABLE_OPENMP=ON \
          -DHAERO_ENABLE_MAM4BOX=OFF \
          -DHAERO_PRECISION=${{ matrix.fp-precision }} \
          -DHAERO_DEVICE_ARCH=AMDAVX \
          -DHAERO_PACK_SIZE=${{ matrix.pack-size}} \
          -G "Unix Makefiles" \
          ..
#          -DOPENBLAS_LIBRARY=/opt/haero/lib/libopenblas.a \
#          -DOPENBLAS_INCLUDE_DIR=/opt/haero/include \
#          -DTINES_LIBRARY=/opt/haero/lib/libtines.a \
#          -DTINES_INCLUDE_DIR=/opt/haero/include \
#          -DTCHEM_LIBRARY=/opt/haero/lib/libtchem.a \
#          -DTCHEM_INCLUDE_DIR=/opt/haero/include \

# TODO: clang-format seems unstable under different versions. Not helpful!
#    - name: Checking code formatting...
#      run: |
#        cd build
#        make format-cxx-check

    - name: Building haero (${{ matrix.build-type }}, ${{ matrix.fp-precision }} precision)
      run: |
        cd build
        make -j

    - name: Running tests (${{ matrix.build-type }}, ${{ matrix.fp-precision }} precision)
      run: |
        cd build
        cp /opt/haero/bin/test-launcher bin
        chmod a+rx bin/test-launcher
        ctest -V

    - name: Installing haero (${{ matrix.build-type }}, ${{ matrix.fp-precision }} precision)
      run: |
        cd build
        make install

